{{- range .Values.domains }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: certbot-{{ .common_name }}
data:
  run.sh: |
    #!/bin/sh
    # Some time for the k8s service to pick up the job pod
    sleep 10

    apk --no-cache add curl

    certbot certonly {{ if $.Values.test_cert }}--test-cert {{ end }}--standalone --preferred-challenges http -d {{ .common_name }}{{- range .subject_alternative_names }} -d {{ . }}{{- end}} -m {{ .contact_mail }} -n --agree-tos

    curl -k \
      --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"  \
      -X PUT \
      -d @- \
      -H 'Accept: application/json' \
      -H 'Content-Type: application/json' \
      https://kubernetes.default.svc/api/v1/namespaces/{{ $.Release.Namespace }}/secrets/certbot-cert <<- EOF
      {
        "kind": "Secret",
        "apiVersion": "v1",
        "metadata": {
          "name": "certbot-cert"
        },
         "type": "kubernetes.io/tls",
        "data": {
          "tls.crt": "$(base64 /etc/letsencrypt/live/{{ .common_name }}/fullchain.pem)",
          "tls.key": "$(base64 /etc/letsencrypt/live/{{ .common_name }}/privkey.pem)"
        }
      }
    EOF
{{ end }}
