apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-updater-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-updater
subjects:
- kind: ServiceAccount
  name: certbot
