apiVersion: v1
kind: Service
metadata:
  name: certbot
  namespace: {{ .Values.namespace }}
  labels:
    app: certbot
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: certbot
