apiVersion: v1
kind: ConfigMap
metadata:
  name: mta-sts
data:
  mta-sts.txt: |
    version: STSv1
    mode: {{ .Values.mta_sts.mode }}
    {{- range .Values.mta_sts.mx_records }}
    mx: {{ . }}
    {{- end }}
    max_age: {{ .Values.mta_sts.max_age }}
