apiVersion: apps/v1
kind: Deployment
metadata:
  name: mta-sts
  labels:
    app.kubernetes.io/name: mta-sts
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mta-sts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mta-sts
    spec:
      serviceAccountName: mta-sts
      containers:
        - name: mta-sts
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            runAsUser: 1000
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: nginx-cache
              mountPath: /var/cache/nginx
              readOnly: false
            - name: var-run
              mountPath: /var/run
              readOnly: false
      volumes:
        - configMap:
            name: mta-sts
          name: nginx-conf
        - name: nginx-cache
          emptyDir: {}
        # needed to register nginx pid
        - name: var-run
          emptyDir: {}
