{{- range .Values.domains }}
{{ $domain := . }}
{{- range .names }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ . }}-master
  annotations:
    nginx.org/mergeable-ingress-type: master
    cert-manager.io/issuer: {{ if $domain.letsencrypt_prod }}  "letsencrypt-prod" {{ else }} "letsencrypt-staging" {{ end }}
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.org/server-snippets: |
      # nginx doest not support multiple if statements
      set $redirect false;
      if ($scheme = http) {
        set $redirect true;
      }
      if ($uri ~ ^/\.well-known/acme-challenge.*) {
        set $redirect false;
      }
      if ($redirect = true) {
        return 308 https://$host:443$request_uri;
      }
{{ if $domain.server_snippets }}
{{ $domain.server_snippets | indent 6 }}
{{ end }}
spec:
  ingressClassName: {{ index $.Values "nginx-ingress" "controller" "ingressClass" }}
  tls:
  - hosts:
    - {{ . }}
    secretName: certbot-{{ . }}
  rules:
  - host: {{ . }}
---
{{ end }}
{{ end }}
