{{- range .Values.domains }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-master
  annotations:
    nginx.org/mergeable-ingress-type: master
    nginx.org/server-snippets: |
      #ssl_dhparam /etc/letsencrypt/dhparams/ssl-dhparams.pem;
      ssl_session_timeout 1d;
      ssl_session_cache shared:{{ .name }}:10m;  # about 40000 sessions
      ssl_session_tickets off;

      # OCSP stapling
      ssl_stapling on;
      ssl_stapling_verify on;

spec:
  ingressClassName: {{ index $.Values "nginx-ingress" "controller" "ingressClass" }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .tls_secret }}
  rules:
  - host: {{ .name }}
---
{{ end }}
