{{- range $profile, $selector := .Values -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-{{ $profile }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ $profile }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-{{ $profile }}-namespaces
roleRef:
  kind: ClusterRole
  name: psp-{{ $profile }}
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- range $selector.namespaces }}
- kind: Group
  name: system:serviceaccounts:{{ . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- range $selector.serviceaccounts }}
- kind: ServiceAccount
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}
---
{{- end }}
