apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeip-sa
subjects:
  - kind: ServiceAccount
    name: kubeip
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kubeip
  apiGroup: rbac.authorization.k8s.io
