apiVersion: v1
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "{{ .Values.gke.clusterName }}"
  KUBEIP_NODEPOOL: "{{ .Values.gke.ingressNodePoolName }}"
  KUBEIP_FORCEASSIGNMENT: "{{ .Values.kubeIp.forceAssignment }}"
  KUBEIP_ADDITIONALNODEPOOLS: ""
  KUBEIP_TICKER: "5"
  KUBEIP_ALLNODEPOOLS: "false"
kind: ConfigMap
metadata:
  labels:
    app: kubeip
  name: kubeip-config
