apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nextcloud-mariadb
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: nextcloud
      ports:
        - port: 3306
          protocol: TCP
  egress:
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nextcloud
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: mariadb
      ports:
        - port: 3306
          protocol: TCP
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: nextcloud
      ports:
        - port: 80
          protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
  policyTypes:
    - Egress

