gke:
  clusterName: ${gkeClusterName}
  ingressNodePoolName: ${gkeIngressNodePoolName}
  generalNodePoolName: ${gkeKubeIpNodePoolName}
nginx-ingress:
  controller:
    nodeSelector:
      cloud.google.com/gke-nodepool: ${gkeIngressNodePoolName}
kubeIp:
  secretName: ${kubeIpKeySecretName}
  privateKey: ${kubeIpPrivateKey}
