gke:
  clusterName: ${gkeClusterName}
  ingressNodePoolName: ${gkeIngressNodePoolName}
  primaryNodePoolName: ${gkePrimaryNodePoolName}
nginx-ingress:
  controller:
    nodeSelector:
      cloud.google.com/gke-nodepool: ${gkeIngressNodePoolName}
nextcloud:
  nodeSelector:
    cloud.google.com/gke-nodepool: ${gkePrimaryNodePoolName}
  mariadb:
    primary:
      nodeSelector:
        cloud.google.com/gke-nodepool: ${gkePrimaryNodePoolName}
kubeIp:
  privateKey: ${kubeIpPrivateKey}
