gke:
  clusterName: ${gkeClusterName}
  ingressNodePoolName: ${gkeNodePoolName}
  generalNodePoolName: ${gkeKubeIpNodePoolName}
kubeIp:
  secretName: ${kubeIpKeySecretName}
  privateKey: ${kubeIpPrivateKey}
